package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if len(os.Args) < 3 {
		os.Exit(1)
	}
	outFile := os.Args[1]
	svgFiles := os.Args[2:]
	sort.Strings(svgFiles)

	icons := make(map[string]string)
	for _, file := range svgFiles {
		content, err := os.ReadFile(file)
		if err != nil {
			os.Exit(1)
		}
		name := strings.TrimSuffix(filepath.Base(file), ".svg")
		icons[name] = strings.TrimSpace(string(content))
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "    ")
	if err := enc.Encode(icons); err != nil {
		os.Exit(1)
	}

	template := `// This file is generated by a Bazel genrule. Do not edit directly.

export const ICONS: Record<string, string> = %s
`

	output := fmt.Sprintf(template, buf.String())

	_ = os.MkdirAll(filepath.Dir(outFile), 0755)
	if err := os.WriteFile(outFile, []byte(output), 0644); err != nil {
		os.Exit(1)
	}
}
