// This file is generated by a Bazel genrule. Do not edit directly.

export const ICONS: Record<string, string> = {
    "circle": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#1e293b\" stroke-width=\"1.75\">\n    <circle cx=\"12\" cy=\"12\" r=\"8.5\"/>\n    <circle cx=\"12\" cy=\"12\" r=\"1.5\" fill=\"#1a73e8\" stroke=\"none\"/>\n</svg>",
    "dimension": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#1e293b\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n    <line x1=\"8\" y1=\"20\" x2=\"4\" y2=\"16\"/>\n    <line x1=\"20\" y1=\"8\" x2=\"16\" y2=\"4\"/>\n    <line x1=\"7.2\" y1=\"12.8\" x2=\"12.8\" y2=\"7.2\" stroke=\"#1a73e8\" stroke-width=\"2\"/>\n    <polygon points=\"5,11 4,16 9,15\" fill=\"#1a73e8\" stroke=\"none\"/>\n    <polygon points=\"11,5 16,4 15,9\" fill=\"#1a73e8\" stroke=\"none\"/>\n</svg>",
    "line": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#1e293b\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n    <line x1=\"5\" y1=\"19\" x2=\"19\" y2=\"5\"/>\n    <circle cx=\"5\" cy=\"19\" r=\"2.5\" fill=\"#1a73e8\" stroke=\"none\"/>\n    <circle cx=\"19\" cy=\"5\" r=\"2.5\" fill=\"#1a73e8\" stroke=\"none\"/>\n</svg>",
    "point": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#1e293b\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n    <circle cx=\"12\" cy=\"12\" r=\"3.5\" fill=\"#1a73e8\" stroke=\"none\"/>\n</svg>",
    "select": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"none\">\n    <polygon points=\"4 3 4 20 9 15 13 21 16 19 12 13 18 13 4 3\" fill=\"#1e293b\"/>\n</svg>"
}

